name: rugby_femenino_api
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  io:
  flutter:
    sdk: flutter

  form_builder_extra_fields: ^11.0.0
  form_builder_validators: ^11.0.0


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
