name: rugby_femenino_api
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  io:
  flutter:
    sdk: flutter

  flutter_form_builder: ^9.5.0
  form_builder_extra_fields: ^11.0.0
  form_builder_validators: ^11.0.0
  flutter_launcher_icons: ^0.14.1

  cupertino_icons: ^1.0.8

  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "./assets/icon.png"
  windows:
    generate: true
    image_path: "./assets/icon.png"